#!/bin/bash

# downloads a local copy of qemu on docker-hub build machines
# changed . to ../ because we are in a subdir

curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static ./
